/*******************************************************************************
 * Copyright 2012 Jeremie Bresson
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package org.eclipselabs.mcqs.shared.services.process;

import java.util.Map;
import java.util.Set;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;
import org.eclipselabs.mcqs.shared.services.lookup.ChoicesLookupCall;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class AnswerFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public AnswerFormData() {
  }

  /**
   * access method for property AnswerNr.
   */
  public Long getAnswerNr() {
    return getAnswerNrProperty().getValue();
  }

  /**
   * access method for property AnswerNr.
   */
  public void setAnswerNr(Long answerNr) {
    getAnswerNrProperty().setValue(answerNr);
  }

  public AnswerNrProperty getAnswerNrProperty() {
    return getPropertyByClass(AnswerNrProperty.class);
  }

  public Choice getChoice() {
    return getFieldByClass(Choice.class);
  }

  public Choices getChoices() {
    return getFieldByClass(Choices.class);
  }

  /**
   * access method for property MultipleChoices.
   */
  public Boolean getMultipleChoices() {
    return getMultipleChoicesProperty().getValue();
  }

  /**
   * access method for property MultipleChoices.
   */
  public void setMultipleChoices(Boolean multipleChoices) {
    getMultipleChoicesProperty().setValue(multipleChoices);
  }

  public MultipleChoicesProperty getMultipleChoicesProperty() {
    return getPropertyByClass(MultipleChoicesProperty.class);
  }

  public QuestionNr getQuestionNr() {
    return getFieldByClass(QuestionNr.class);
  }

  public QuestionText getQuestionText() {
    return getFieldByClass(QuestionText.class);
  }

  public YourName getYourName() {
    return getFieldByClass(YourName.class);
  }

  public static class AnswerNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;

    public AnswerNrProperty() {
    }
  }

  public static class Choice extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;

    public Choice() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.LOOKUP_CALL, ChoicesLookupCall.class);
      ruleMap.put(ValidationRule.MASTER_VALUE_FIELD, QuestionNr.class);
      ruleMap.put(ValidationRule.ZERO_NULL_EQUALITY, true);
    }
  }

  public static class Choices extends AbstractValueFieldData<Set<Long>> {

    private static final long serialVersionUID = 1L;

    public Choices() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.LOOKUP_CALL, ChoicesLookupCall.class);
      ruleMap.put(ValidationRule.MASTER_VALUE_FIELD, QuestionNr.class);
    }
  }

  public static class MultipleChoicesProperty extends AbstractPropertyData<Boolean> {

    private static final long serialVersionUID = 1L;

    public MultipleChoicesProperty() {
    }
  }

  public static class QuestionNr extends AbstractValueFieldData<Integer> {

    private static final long serialVersionUID = 1L;

    public QuestionNr() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_VALUE, Integer.MAX_VALUE);
      ruleMap.put(ValidationRule.MIN_VALUE, Integer.MIN_VALUE);
    }
  }

  public static class QuestionText extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public QuestionText() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class YourName extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public YourName() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MANDATORY, true);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }
}
