CREATE TABLE MCQ.QUESTIONS
(
   QUESTION_ID INTEGER NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   QUESTION_TEXT VARCHAR(512) NOT NULL,
   MULTIPLE_CHOICES SMALLINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX QUESTIONS_INDEX ON MCQ.QUESTIONS (QUESTION_ID);

CREATE TABLE MCQ.CHOICES
(
   CHOICE_ID INTEGER NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   CHOICE_TEXT VARCHAR(256) NOT NULL,
   QUESTION_ID INTEGER NOT NULL
);

CREATE UNIQUE INDEX CHOICES_INDEX ON MCQ.CHOICES(CHOICE_ID);

CREATE TABLE MCQ.ANSWERS
(
   ANSWER_ID INTEGER NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   NAME VARCHAR(128),
   QUESTION_ID INTEGER NOT NULL
);

CREATE UNIQUE INDEX ANSWERS_INDEX ON MCQ.ANSWERS(ANSWER_ID);

CREATE TABLE MCQ.ANSWERS_CHOICES
(
   ANSWER_ID INTEGER NOT NULL,
   CHOICE_ID INTEGER NOT NULL
);

CREATE UNIQUE INDEX ANSWERS_CHOICES_INDEX ON MCQ.ANSWERS_CHOICES (ANSWER_ID, CHOICE_ID);

ALTER TABLE MCQ.CHOICES
ADD FOREIGN KEY (QUESTION_ID) 
REFERENCES MCQ.QUESTIONS(QUESTION_ID);

ALTER TABLE MCQ.ANSWERS
ADD FOREIGN KEY (QUESTION_ID) 
REFERENCES MCQ.QUESTIONS(QUESTION_ID);

ALTER TABLE MCQ.ANSWERS_CHOICES
ADD FOREIGN KEY (ANSWER_ID) 
REFERENCES MCQ.ANSWERS(ANSWER_ID);

ALTER TABLE MCQ.ANSWERS_CHOICES
ADD FOREIGN KEY (CHOICE_ID) 
REFERENCES MCQ.CHOICES(CHOICE_ID);